### ISSUE TITLE
Question about reliability model result

### ISSUE THREAD

**Issue by hrchu** [ceph/ceph-tools#4]
(Issue updated)

Hi, I have tried the reliability model with default configuration, and cannot understand the result.

```
    storage               durability    PL(site)  PL(copies)     PL(NRE)     PL(rep)    loss/PiB
    ----------            ----------  ----------  ----------  ----------  ----------  ----------
    Disk: Enterprise         99.119%   0.000e+00   0.721457%   0.159744%   0.000e+00   8.812e+12
    RADOS: 1 cp              99.279%   0.000e+00   0.721457%   0.000865%   0.000e+00   5.411e+12
    RADOS: 2 cp              7-nines   0.000e+00   0.000049%   0.003442%   0.000e+00   9.704e+06
    RADOS: 3 cp             11-nines   0.000e+00   5.090e-11   3.541e-09   0.000e+00   6.655e+02
```

```
    storage               durability    PL(site)  PL(copies)     PL(NRE)     PL(rep)    loss/PiB
    ----------            ----------  ----------  ----------  ----------  ----------  ----------
    Site (1 PB)              99.900%   0.099950%   0.000e+00   0.000e+00   0.000e+00   9.995e+11
    RADOS: 1-site, 1-cp      99.179%   0.099950%   0.721457%   0.000865%   0.000e+00   1.010e+12
    RADOS: 1-site, 2-cp      99.900%   0.099950%   0.000049%   0.003442%   0.000e+00   9.995e+11
    RADOS: 1-site, 3-cp      99.900%   0.099950%   5.090e-11   3.541e-09   0.000e+00   9.995e+11

```

The two result tables have different trend. In the first table, durability value is 1 cp < 2 cp < 3 cp. However, the second table results in 1 cp < 2 cp = 3 cp. 

The two tables have the same PL(site),  PL(copies) , PL(NRE), and PL(rep). The only difference is PL(site). PL(site) is constant, since number of site is constant. The trend should be the same.

How to explain the result?

Anything I missed out? Thanks

**Comment by gregsfortytwo** [comment]
Please send queries for help to the user list (ceph-users@ceph.com); we don't regularly monitor the github issue tracker!

**Comment by hrchu** [comment]
Hi, I have cross post this issue to https://www.mail-archive.com/ceph-users@lists.ceph.com/msg22224.html

and have not get response yet :pensive:

**Comment by dmick** [comment]
That's sad, but it's still the right place, not here.
